### PR TITLE
Yggdradil Update: HMAS Ontology, refactor, updated dependencies & build tools and various smaller changes

### PR DESCRIPTION
**Pull request by KaiTries**
Main changes:

- Versioning: updated most dependencies to more recent versions.
  -  Gradle: version 8.9 is now used
  -  WoT-TD-Java library: v1.2 -> newest MainSnapshot
  -  Cartago library: dedicated [fork](https://github.com/KaiTries/cartago/tree/yggdrasil) but still local jar dependency -> Updated versions + additional functionality to remove workspaces.
  -  currently used versions of different dependencies can be found [here](https://github.com/Interactions-HSG/yggdrasil/blob/main/gradle/libs.versions.toml). 
-  Support for multiple Ontologies & HMAS implementation
   -  Yggdrasil now runs agnostic of the underlying ontology, which enables easy switching between and adding of different ontologies. To enable a different ontology all you have to do is create a new Implementation of the RepresentationFactory interface and add it to the RepresentationFactoryFactory. 
   - To choose a specific ontology a new key value pair can be added to the conf file in the environment-config part. The value corresponds to the chosen identifier in the RepresentationFactoryFactory. (This works even if the environment-config is disabled):
   ``` 
   {
     "environment-config" : 
     {
       "ontology": "td"
     }
   }
   ```
   - If you want to add a HypermediaArtifact on a new ontology all you have to do is implement the HypermediaArtifact interface.
- Improved agent handling. <- This should also solve some points mentioned by matteo
   - No longer constrained to specific agent WebID.
   - New header "X-Agent-LocalName" : "wantedName" <- If the name is available it will be used for the bodyArtifact otherwise a random UUID will be used.
   - the /agents/ path is no longer used. Agent body artifact are now also located in the /artifacts/ path. 
- New Artifact functionality & API
   - The output of an action must now be specified in the same manner that the input must be specified! 
      - The api for registering actions has therefore changed
      - Also due to the change of the HypermediaArtifact registry no longer being a singleton, the getApiKey() method has also been moved to the artifact 
   - Multiple feedback parameters are now supported.
   - Signals are now also supported.
   - Currently we are still restricted to only supporting list input & output. 
-  Refactoring of HypermediaArtifactRegistry
   - Is no longer a Singleton and is now only used in the CartagoVerticle through dependency injection. This enables stronger decoupling and helped clean up the code a little. 
-  Various changes:
   -  Deletion of all entities works correctly now. Workspaces can also be properly deleted in the cartago instance. 
   -  Namespace handling is improved. Representations will only use those that they actually need & new representations are added at runtime as well. 
   - Using @base to give a bit of a cleaner look. The @base is the baseUri for the yggdrasil instance.
   - Making the representation for an entity is now decoupled from the CartagoVerticle. This enables uniformity between the different kinds of artifacts. 
   - Probably various other smaller changes

### CODE REVIEW

**Comment by KaiTries** [comment]
TO-DOs before merge:

- Conditional exposure of WebSub Signifiers
- Fixing bug that alters representation of workspace given by file and enabled environment

**Comment by KaiTries** [comment]
TD ontology wraps Thing Descriptions in ResourceProfiles to more closely represent the resources.

- No breaking changes, overall logic stays the same. 
- Each workspace, artifact, agent body artifact, are now generated with two additional triples: 
    -  <resourceIRI> rdf:Type <hmas:ResourceProfile>
    - <resourceIRI> hmas:isProfileOf <resourceIRI + #(workspace / artifact)>

**Comment by danaivach** [comment]
@KaiTries, I observe the following issue:

Agent bodies are initialized as CArtAgO artifacts, but focusing on them leads to a `NullPointerException` and a 500 server error. 

**Probable Reason**
In [`CartagoVerticle.focus()`](https://github.com/KaiTries/yggdrasil/blob/f3d7f2cfa1b0d542becfee475a70d425e7a1c5fb/yggdrasil-cartago/src/main/java/org/hyperagents/yggdrasil/cartago/CartagoVerticle.java#L337-L357), the body artifact name is passed as `artifactName` (e.g.  `artifactName = agent0`, given that bodies are named based on the `X-Agent-LocalName` header value). 

However, in `Workspace.makeAgentBodyArtifact()` (cartago 3.2), body artifacts are initialized with names in the form `"body_" + body.getAgentId().getAgentName()`  (e.g, `body_https://wiser-solid-xi.interactions.ics.unisg.ch/agent0/profile/card#me`, given that agents are named based on the `X-Agent-WebID`). 

Therefore, the body artifact cannot be found in the workspace due to name mismatch (probably [line 349](https://github.com/KaiTries/yggdrasil/blob/f3d7f2cfa1b0d542becfee475a70d425e7a1c5fb/yggdrasil-cartago/src/main/java/org/hyperagents/yggdrasil/cartago/CartagoVerticle.java#L349)).

**To reproduce** 
- Join a workspace
```
curl --location --request POST 'http://172.27.52.55:8080/workspaces/61/join' \
--header 'X-Agent-WebID: https://wiser-solid-xi.interactions.ics.unisg.ch/agent-a/profile/card#me' \
--header 'X-Agent-LocalName: agent0'
```

- Focus on the body of the joined agent
```
curl --location 'http://172.27.52.55:8080/workspaces/61/focus' \
--header 'X-Agent-WebID: https://wiser-solid-xi.interactions.ics.unisg.ch/agent-n/profile/card#me' \
--header 'Content-Type: application/json' \
--data '{
    "artifactName" : "agent0",
    "callbackIri" : "http://localhost:8081/notifications/"
}'
```

**Comment by KaiTries** [comment]
Thanks for the detailed report @danaivach. This issue went under the radar because we only tested for focusing on workspaces and artifacts.

- Added additional test to ensure that an agent body artifact can also be focused on.
- To integrate more easily with cartago, the agent name will automatically be prepended with "body_" so that it works internally. This just means that the locations of agent bodies in yggdrasil will uniformely look like this:
    - https://yggdrasil-node.com/workspace/artifacts/body_agentname/
    - When joining through an http request you do not need to add the "body_" part just normally add the webID and prefered agent name.

**Pull request merged**
